import type { Component, DensityType, ElevationProps, RoundedType, SizeType } from '$lib/@types';
import type { Snippet } from 'svelte';
import type { HTMLInputAttributes } from 'svelte/elements';

export interface TextfieldProps extends Component {
	ref?: HTMLElement | null;
	value?: string | number;
	type?: 'text' | 'email' | 'password' | 'number';
	placeholder?: string;
	counter?: boolean;
	min?: number;
	max?: number;
	variant?: 'outline' | 'text' | 'filled';
	density?: DensityType;
	error?: boolean;
	errorMessage?: string;
	disabled?: boolean;
	color?: string;
	background?: string;
	size?: SizeType;
	rounded?: RoundedType;
	readonly?: boolean;
	hideSpinButtons?: boolean;
	persistentMessage?: boolean;
	persistentClear?: boolean;
	clearable?: boolean;
	message?: string;
	messagePrefix?: string;
	messageSuffix?: string;
	append?: Snippet;
	prepend?: Snippet;
	prependInner?: Snippet;
	appendInner?: Snippet;
	prefix?: string;
	suffix?: string;
	name?: string;
	id?: string;
	autocomplete?: HTMLInputAttributes['autocomplete'];
	inputmode?: HTMLInputAttributes['inputmode'];
	elevation?: ElevationProps;
}
